---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Qubes OS creates the file `01qubes-proxy` in template VMs.
# In AppVMs, the file is deleted by Qubes OS, in such cases, the default of `00apt_proxy` will become active.

apt_proxy__proxy_auto_detect: '{{ "/usr/local.template/lib/get-reachable-apt-proxy"
                                  if (apt_proxy__temporally_avoid_unreachable|d(False)|bool)
                                  else omit }}'
