---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# `molly-guard` is handled on Ansible host group level.
sshd__optional_packages: []


## Upper limit 255.
sshd__ferm_limit_hits: '255'

sshd__ferm_limit_seconds: '{{ (60 * 2) }}'

sshd__use_dns: 'no'
