---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

sshd__permit_root_login: 'no'
sshd__paranoid: True
sshd__allow_groups:
  # - 'root'
  - 'admins'
  - 'sshusers'
  - 'sftponly'

sshd__allow_tcp_forwarding: 'no'
sshd__use_dns: 'yes'

sshd__custom_options: |
  ServerKeyBits 4096
  RSAAuthentication no
  PermitUserEnvironment no
  DebianBanner no

  AllowAgentForwarding no

  {% if sshd__register_version.stdout|d() and sshd__register_version.stdout|version_compare('7.4', '>=') %}
  ## https://www.openssh.com/txt/release-7.4
  DisableForwarding {{ sshd__allow_tcp_forwarding|d("yes") }}
  {% endif %}

  # Default:
  GatewayPorts no

  AllowTcpForwarding {{ sshd__allow_tcp_forwarding|d("yes") }}

  UseDNS {{ sshd__use_dns|d("yes") }}


sshd__host_keys: [ 'ed25519', 'rsa' ]

sshd__ciphers_map:

  '6.5': [ 'aes256-gcm@openssh.com' ]
  '6.0': [ 'aes256-ctr' ]

sshd__kex_algorithms_map:

  '6.0': [ 'curve25519-sha256@libssh.org' ]
