---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

ansible_facts__core__domain: '{{
  ansible_local.core.domain
  if (ansible_local|d() and ansible_local.core|d() and
    ansible_local.core.domain|d())
  else (ansible_domain|d(inventory_hostname.split(".")[1:] | join("."))) }}'
